### ISSUE TITLE
老哥上岸了没有？

### ISSUE THREAD

**Issue by whyalwaysmea** [kuriv/civil-service-exam#1]

**Comment by kuriv** [comment]
老弟你好！因为参加的是2019年下半年的四川省考，12月中旬刚刚公布考试分数，岗位排名预计在12月下旬公布。某公的晒分排名及分差查询系统上暂居榜首，不过仅供参考。后续的任何进展，我会更新在这里。

**Comment by whyalwaysmea** [comment]
我也是参加的2019年下半年的四川省考，估计没法进面了。如果可以留个更方便的联系方式多交流一下？

**Comment by kuriv** [comment]
![微信图片_20191217221228](https://user-images.githubusercontent.com/25667547/71002491-58266900-211a-11ea-8b7f-4db9aae7076b.jpg)

**Comment by kuriv** [comment]
![总成绩](https://user-images.githubusercontent.com/25667547/72492159-358d8a00-3857-11ea-8461-8adc40d2afc6.png)

**Comment by haiya512** [comment]
老哥，可以啊，我第一次考试没进面试，想问问你现在工作感受如何？

**Comment by kuriv** [comment]
别沮丧，第一次就当是练下手，努力都会有回报，选岗比分数更重要。我报的是司法局，待遇还可以，平时工作不忙。

**Comment by haiya512** [comment]
我虽然转了IT，但我的专业限制了我只能报考三不限的。
